# ブログ関連設定ファイル
#
# @package org.carrot-framework
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id: blog.yaml 2453 2011-01-05 02:45:48Z pooza $

ping:
  urls:
    - http://api.my.yahoo.co.jp/RPC2
    - http://blogsearch.google.co.jp/ping/RPC2
    - http://blog.goo.ne.jp/XMLRPC
    - http://ping.fc2.com/
    - http://rpc.reader.livedoor.com/ping
