# 日付関連設定ファイル
#
# @package org.carrot-framework
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id: date.yaml 1812 2010-02-03 15:15:09Z pooza $

gengo:
  - name: 平成
    start_date: 1989-01-08
  - name: 昭和
    start_date: 1926-12-25
  - name: 大正
    start_date: 1912-07-30
# タイムスタンプが生成出来ない。
# - name: 明治
#   start_date: 1868-09-08

holiday:
  ja:
    class: BSJapaneseHolidayListService
