# メディアタイプ設定ファイル
#
# @package org.carrot-framework
# @author 小石達也 <tkoishi@b-shock.co.jp>

types:
  3gp: video/3gpp
  3g2: video/3gpp2
  aac: audio/x-aac
  ai: application/postscript
  aif: audio/x-aiff
  as:
  atom: application/atom+xml
  css: text/css
  csv: text/csv
  dat: application/octet-stream
  dmt: application/x-decomail-template
  doc: application/vnd.ms-word
  docx: application/vnd.openxmlformats-officedocument.wordprocessingml.document
  eml: message/rfc822
  eps: application/eps
  flv: video/x-flv
  gif: image/gif
  gz: application/x-gzip
  hmt: application/x-htmlmail-template
  html: text/html
  ico: image/vnd.microsoft.icon
  ini: text/x-ini-file
  jpg: image/jpeg
  js: text/javascript
  json: application/json
  khm: application/x-kddi-htmlmail
  m4a: audio/mp4
  mov: video/quicktime
  mp3: audio/mpeg
  mp4: video/mp4
  mpg: video/mpeg
  odp: application/vnd.oasis.opendocument.presentation
  ods: application/vnd.oasis.opendocument.spreadsheet
  odt: application/vnd.oasis.opendocument.text
  pdf: application/pdf
  php:
  pl:
  pm:
  png: image/png
  ppt: application/vnd.ms-powerpoint
  pptx: application/vnd.openxmlformats-officedocument.presentationml.presentation
  rb:
  sql:
  swf: application/x-shockwave-flash
  tif: image/tiff
  tpl: text/x-smarty-template
  ttf: application/x-truetype-font
  txt: text/plain
  wma: audio/x-ms-wma
  wav: audio/x-wav
  webm: video/webm
  wmv: video/x-ms-wmv
  yaml: text/yaml
  xhtml: application/xhtml+xml
  xls: application/vnd.ms-excel
  xlsx: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
  xml: application/xml
  vcf: text/x-vcard
  zip: application/zip
