# 機種依存文字の変換テーブル
#
# @package org.carrot-framework
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @link http://php.nekosuke.com/000056.htm 参考

- search: \xE2\x85\xA0
  replace: I
- search: \xE2\x85\xA1
  replace: II
- search: \xE2\x85\xA2
  replace: III
- search: \xE2\x85\xA3
  replace: IV
- search: \xE2\x85\xA4
  replace: V
- search: \xE2\x85\xA5
  replace: VI
- search: \xE2\x85\xA6
  replace: VII
- search: \xE2\x85\xA7
  replace: VIII
- search: \xE2\x85\xA8
  replace: IX
- search: \xE2\x85\xA9
  replace: X
- search: \xE2\x85\xB0
  replace: i
- search: \xE2\x85\xB1
  replace: ii
- search: \xE2\x85\xB2
  replace: iii
- search: \xE2\x85\xB3
  replace: iv
- search: \xE2\x85\xB4
  replace: v
- search: \xE2\x85\xB5
  replace: vi
- search: \xE2\x85\xB6
  replace: vii
- search: \xE2\x85\xB7
  replace: viii
- search: \xE2\x85\xB8
  replace: ix
- search: \xE2\x85\xB9
  replace: x
- search: \xE2\x91\xA0
  replace: (1)
- search: \xE2\x91\xA1
  replace: (2)
- search: \xE2\x91\xA2
  replace: (3)
- search: \xE2\x91\xA3
  replace: (4)
- search: \xE2\x91\xA4
  replace: (5)
- search: \xE2\x91\xA5
  replace: (6)
- search: \xE2\x91\xA6
  replace: (7)
- search: \xE2\x91\xA7
  replace: (8)
- search: \xE2\x91\xA8
  replace: (9)
- search: \xE2\x91\xA9
  replace: (10)
- search: \xE2\x91\xAA
  replace: (11)
- search: \xE2\x91\xAB
  replace: (12)
- search: \xE2\x91\xAC
  replace: (13)
- search: \xE2\x91\xAD
  replace: (14)
- search: \xE2\x91\xAE
  replace: (15)
- search: \xE2\x91\xAF
  replace: (16)
- search: \xE2\x91\xB0
  replace: (17)
- search: \xE2\x91\xB1
  replace: (18)
- search: \xE2\x91\xB2
  replace: (19)
- search: \xE2\x91\xB3
  replace: (20)
- search: \xE3\x8A\xA4
  replace: (上)
- search: \xE3\x8A\xA5
  replace: (中)
- search: \xE3\x8A\xA6
  replace: (下)
- search: \xE3\x8A\xA7
  replace: (左)
- search: \xE3\x8A\xA8
  replace: (右)
- search: \xE3\x8D\x89
  replace: ミリ
- search: \xE3\x8D\x8D
  replace: メートル
- search: \xE3\x8C\x94
  replace: キロ
- search: \xE3\x8C\x98
  replace: グラム
- search: \xE3\x8C\xA7
  replace: トン
- search: \xE3\x8C\xA6
  replace: ドル
- search: \xE3\x8D\x91
  replace: リットル
- search: \xE3\x8C\xAB
  replace: パーセント
- search: \xE3\x8C\xA2
  replace: センチ
- search: \xE3\x8E\x9D
  replace: cm
- search: \xE3\x8E\x8F
  replace: kg
- search: \xE3\x8E\xA1
  replace: m2
- search: \xE3\x8F\x8D
  replace: K.K.
- search: \xE2\x84\xA1
  replace: TEL
- search: \xE2\x84\x96
  replace: No.
- search: \xE3\x8D\xBB
  replace: 平成
- search: \xE3\x8D\xBC
  replace: 昭和
- search: \xE3\x8D\xBD
  replace: 大正
- search: \xE3\x8D\xBE
  replace: 明治
- search: \xE3\x88\xB1
  replace: (株)
- search: \xE3\x88\xB2
  replace: (有)
- search: \xE3\x88\xB9
  replace: (代)
