# フォント設定ファイル
#
# @package org.carrot-framework
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id: color.yaml 506 2008-08-20 09:23:40Z pooza $

VL-PGothic-Regular:
  name:
    ja: VL Pゴシック
  aspect: 0.9
MSPMincho:
  name:
    ja: ＭＳ Ｐ明朝
MSPGothic:
  name:
    ja: ＭＳ Ｐゴシック
