# UserAgent設定ファイル
#
# @package org.carrot-framework
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id: carrot.yaml 1812 2010-02-03 15:15:09Z pooza $

Tasman:
  denied: yes
LegacyMozilla:
  denied: yes
Trident:
  legacy_denied: yes
Docomo:
  legacy_denied: yes
  denied_patterns:
    - D20
    - D21
    - D25
    - D50
    - D2101V
    - ER209i
    - F20
    - F21
    - F25
    - F50
    - F661i
    - F671i
    - F671iS
    - F672i
    - F880iES
    - F881iES
    - F2101V
    - KO209i
    - KO210i
    - N20
    - N21
    - N25
    - N50
    - N821i
    - NM502i
    - P20
    - P21
    - P25
    - P50
    - P821i
    - P253i
    - P253iS
    - R209i
    - R211i
    - R691i
    - R692i
    - SH25
    - SH50
    - SH821i
    - SO21
    - SO50
    - NM850iG
    - F2051
Au:
  legacy_denied: yes
  denied_patterns:
    - ST14
    - HI14
    - HI22
    - KC13
    - KC14
    - KC15
    - KC26
    - KCU1
    - ST11
    - ST13
    - SY15
    - SY14
    - SY13
    - SY12
    - SYT4
    - MA13
    - CA13
    - SN12
    - SN14
    - SN15
    - SN16
    - SN17
    - DN11
    - CA14
    - TS14
SoftBank:
  legacy_denied: yes
  denied_patterns:
    - 304T
    - C980
    - J-D03
    - J-D04
    - J-D05
    - J-D06
    - J-D07
    - J-D08
    - J-D31
    - J-DN02
    - J-DN03
    - J-K03
    - J-K04
    - J-K05
    - J-K51
    - J-N03
    - J-N04
    - J-N05
    - J-N51
    - J-NM01
    - J-NM02
    - J-P02
    - J-P03
    - J-P51
    - J-PE03
    - J-SA02
    - J-SA03
    - J-SA04
    - J-SA05
    - J-SA06
    - J-SA51
    - J-SH01
    - J-SH02
    - J-SH03
    - J-SH04
    - J-SH05
    - J-SH06
    - J-SH07
    - J-SH08
    - J-SH09
    - J-SH010
    - J-SH51
    - J-SH52
    - J-SH53
    - J-T010
    - J-T04
    - J-T05
    - J-T06
    - J-T07
    - J-T08
    - J-T09
    - J-T51
    - V201
    - V102
    - V401
    - V402
    - V403
    - V301
    - V302
    - V303
    - V601
    - V603

