# メニュー設定ファイル - 管理メニュー
#
# @package jo.co.commons.forms.mail
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id$

- separator: yes
- module: AdminLog
- module: DevelopTableReport
- title: アクセスログ解析
  href: /awstats/awstats.pl
  target: _blank
  credential: Admin
- separator: yes
- title: ログアウト
  module: Default
  action: Logout