# メニュー設定ファイル - 管理メニュー
#
# @package jp.co.b-shock.forms.mail
# @author 小石達也 <tkoishi@b-shock.co.jp>

- module: AdminConnection
- separator: yes
- module: AdminLog
- module: DevelopTableReport
- title: アクセスログ解析
  href: /awstats/awstats.pl
  target: _blank
  credential: Admin
- separator: yes
- title: ログアウト
  module: Default
  action: Logout