# フィルタ設定ファイル
#
# @package jo.co.commons.forms.mail
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id$

- class: BSFakeUserAgentFilter
- class: BSLegacyUserAgentFilter
- class: BSPictogramRequestFilter
- class: BSEncodingRequestFilter
- class: BSNewLineRequestFilter
- class: BSCookieFilter
- class: BSKanaRequestFilter
  params:
    option: KVa
- class: BSReadingRequestFilter
- class: BSDateRequestFilter
