# フィルタ設定ファイル
#
# @package jp.co.b-shock.forms.mail
# @author 小石達也 <tkoishi@b-shock.co.jp>

- class: BSFakeUserAgentFilter
- class: BSLegacyUserAgentFilter
- class: BSPictogramRequestFilter
- class: BSEncodingRequestFilter
- class: BSNewLineRequestFilter
- class: BSCookieFilter
- class: BSKanaRequestFilter
  params:
    option: KVa
- class: BSReadingRequestFilter
- class: BSDateRequestFilter
