# アプリケーション定数設定ファイル
#
# @package jo.co.commons.forms.mail
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id$

app:
  name:
    ja: FORMS-MAIL
    en: FORMS-MAIL
  ver: 1.0.0

crypt:
  salt: I8BDT76KZX6Z6IIE
