# ホスト別設定ファイル
#
# @package jo.co.commons.forms.mail
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id$

root_url: http://mail.forms.glaive.local/
root_url_https: http://mail.forms.glaive.local/
debug: yes

admin:
  email: admin@b-shock.co.jp
  password: 7e240de74fb1ed08fa08d38063f6a6a91462a815
  networks:
    - 192.168.102.0/24

author:
  name: 有限会社 ビーショック
  email: info@b-shock.co.jp

crypt:
  salt: FSKJB7LYUW

pdo:
  default:
    dsn: mysql:host=127.0.0.1;dbname=forms_mail
    uid: root
    password:

mysql:
  dir: /opt/local/lib/mysql5
