# ホスト別設定ファイル
#
# @package jp.co.b-shock.forms.mail
# @author 小石達也 <tkoishi@b-shock.co.jp>

root_url: http://mail.forms.toroid.local/
root_url_https: http://mail.forms.toroid.local/
debug: yes

admin:
  email: admin@b-shock.co.jp
  password: 7e240de74fb1ed08fa08d38063f6a6a91462a815
  networks:
    - 192.168.0.0/24
    - 192.168.1.0/24
    - 192.168.101.0/24

author:
  name: 有限会社 ビーショック
  email: info@b-shock.co.jp

app:
  name:
    ja: 美食メールマガジン
    en: b-shock. Mail Magazine
  process:
    uid: www

crypt:
  salt: FSKJB7LYUW

pdo:
  default:
    dsn: mysql:host=127.0.0.1;dbname=forms_mail
    uid: root
    password:

mysql:
  dir: /opt/local/lib/mysql5
