# アプリケーション定数設定ファイル - パッケージ分
#
# @package jo.co.commons.forms.mail
# @author 小石達也 <tkoishi@b-shock.co.jp>

package:
  name: forms-mail
  ver: 1.0.0b1

crypt:
  salt: I8BDT76KZX6Z6IIE

module:
  prefixes:
    - Admin
    - User
    - Develop
    - Console
    - Agent
