# アプリケーション定数設定ファイル - パッケージ分
#
# @package jp.co.b-shock.forms.mail
# @author 小石達也 <tkoishi@b-shock.co.jp>

package:
  name: forms-mail
  ver: 1.0.1

crypt:
  salt: I8BDT76KZX6Z6IIE

image:
  qrcode:
    size: 80
