# JavaScriptセット設定ファイル
#
# @package org.carrot-framework
# @author 小石達也 <tkoishi@b-shock.co.jp>

carrot:
  files:
    - prototype
    - scriptaculous/effects
    - scriptaculous/builder
    - scriptaculous/dragdrop
    - scriptaculous/slider
    - ajaxzip3
    - lightbox
    - prototabs
    - protocalendar/protocalendar
    - protocalendar/lang_ja
    - usermenu
    - elevator
    - yahoo.color
    - color_picker
    - carrot
    - application
lightpop:
  files:
    - jquery.lightpop
