# スタイルセット設定ファイル
#
# @package org.carrot-framework
# @author 小石達也 <tkoishi@b-shock.co.jp>

carrot:
  files:
    - html5-reset
    - carrot
    - protocalendar
    - prototabs
    - lightbox
    - color_picker
    - application
