# スタイルセット設定ファイル
#
# @package org.carrot-framework
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id: carrot.yaml 2231 2010-07-26 08:39:04Z pooza $

carrot:
  files:
    - carrot
    - protocalendar
    - prototabs
    - application

carrot.Detail:
  files:
    - carrot
    - carrot.Detail
    - protocalendar
    - prototabs
    - lightbox
    - color_picker
    - application

carrot.LoginForm:
  files:
    - carrot
    - carrot.LoginForm
    - application
